const LANGUAGES = [
  {
    name: 'العربية', code: 'AR',
    dialects: [
      { name: 'فصحى', api: 'Arabic', aliases: ['العربية', 'AR', 'ar', 'عامة', 'فصحى', 'الفصحى'] },
      { name: 'الجزائرية', api: 'Algerian Arabic' },
      { name: 'المصرية', api: 'Egyptian Arabic' },
      { name: 'العراقية', api: 'Iraqi Arabic' },
      { name: 'اللبنانية', api: 'Lebanese Arabic' },
      { name: 'الليبية', api: 'Libyan Arabic' },
      { name: 'الدارجة المغربية', api: 'Moroccan Darija' },
      { name: 'السعودية', api: 'Saudi Arabic' },
      { name: 'السورية', api: 'Syrian Arabic' },
      { name: 'التونسية', api: 'Tunisian Arabic' },
      { name: 'اليمنية', api: 'Yemeni Arabic' },
      { name: 'الأردنية', api: 'Arabic (Jordanian)' },
      { name: 'الإماراتية', api: 'Emirati Arabic' },
      { name: 'البحرينية', api: 'Arabic (Bahraini)' },
      { name: 'العُمانية', api: 'Arabic (Omani)' },
      { name: 'القطرية', api: 'Qatari Arabic' },
      { name: 'الكويتية', api: 'Arabic (Kuwaiti)' },
    ]
  },
  {
    name: 'الإنجليزية', code: 'EN',
    dialects: [
      { name: 'الأمريكية', api: 'English US' },
      { name: 'الأسترالية', api: 'English (Australian)' },
      { name: 'الأيرلندية', api: 'English (Irish)' },
      { name: 'البريطانية', api: 'English (British)' },
      { name: 'التنزانية', api: 'English (Tanzanian)' },
      { name: 'السنغافورية', api: 'English (Singaporean)' },
      { name: 'الفلبينية', api: 'English (Philippine)' },
      { name: 'الكندية', api: 'English (Canadian)' },
      { name: 'الكينية', api: 'English (Kenyan)' },
      { name: 'النيجيرية', api: 'English (Nigerian)' },
      { name: 'الهندية', api: 'English (Indian)' },
      { name: 'الجنوب أفريقية', api: 'English (South African)' },
      { name: 'النيوزيلندية', api: 'English (New Zealand)' },
      { name: 'هونغ كونغ', api: 'English (Hong Kong)' },
    ]
  },
  {
    name: 'الإسبانية', code: 'ES',
    dialects: [
      { name: 'العامة', api: 'Spanish' },
      { name: 'الأرجنتينية', api: 'Argentine Spanish' },
      { name: 'الأمريكية', api: 'Spanish (American)' },
      { name: 'الأوروغوايانية', api: 'Uruguayan Spanish' },
      { name: 'الإكوادورية', api: 'Spanish (Ecuadorian)' },
      { name: 'الباراغوايانية', api: 'Paraguayan Spanish' },
      { name: 'البنمية', api: 'Spanish (Panamanian)' },
      { name: 'البورتوريكية', api: 'Puerto Rican Spanish' },
      { name: 'البوليفية', api: 'Spanish (Bolivian)' },
      { name: 'البيروفية', api: 'Peruvian Spanish' },
      { name: 'التشيلية', api: 'Chilean Spanish' },
      { name: 'الدومينيكية', api: 'Dominican Spanish' },
      { name: 'السلفادورية', api: 'Spanish (Salvadoran)' },
      { name: 'الغواتيمالية', api: 'Spanish (Guatemalan)' },
      { name: 'الغينية الاستوائية', api: 'Spanish (Equatoguinean)' },
      { name: 'الفنزويلية', api: 'Venezuelan Spanish' },
      { name: 'الكوبية', api: 'Cuban Spanish' },
      { name: 'الكوستاريكية', api: 'Spanish (Costa Rican)' },
      { name: 'الكولومبية', api: 'Colombian Spanish' },
      { name: 'المكسيكية', api: 'Mexican Spanish' },
      { name: 'النيكاراغوية', api: 'Spanish (Nicaraguan)' },
      { name: 'الهندوراسية', api: 'Spanish (Honduran)' },
    ]
  },
  {
    name: 'البرتغالية', code: 'PT',
    dialects: [
      { name: 'العامة (البرتغال)', api: 'Portuguese' },
      { name: 'البرازيلية', api: 'Brazilian Portuguese' },
    ]
  },
  {
    name: 'الألمانية', code: 'DE',
    dialects: [
      { name: 'العامة (ألمانيا)', api: 'German' },
      { name: 'السويسرية', api: 'Swiss German' },
      { name: 'النمساوية', api: 'Austrian German' },
    ]
  },
  {
    name: 'الفرنسية', code: 'FR',
    dialects: [
      { name: 'العامة (فرنسا)', api: 'French' },
      { name: 'البلجيكية', api: 'Belgian French' },
      { name: 'السويسرية', api: 'French (Swiss)' },
      { name: 'الكندية', api: 'Canadian French' },
    ]
  },
  {
    name: 'الصينية', code: 'ZH',
    dialects: [
      { name: 'العامة (ماندرين)', api: 'Chinese' },
      { name: 'التايوانية', api: 'Taiwan Mandarin' },
      { name: 'الكانتونية (هونغ كونغ)', api: 'Hong Kong Cantonese' },
      { name: 'الكانتونية المبسطة', api: 'Simplified Cantonese' },
      { name: 'جيلو ماندرين', api: 'Jilu Mandarin' },
      { name: 'سيتشوان ماندرين', api: 'Sichuan Mandarin' },
      { name: 'الشنغهاينية (وو)', api: 'Wu Chinese (Shanghainese)' },
    ]
  },
  {
    name: 'الهولندية', code: 'NL',
    dialects: [
      { name: 'هولندا', api: 'Dutch (Netherlands)' },
      { name: 'البلجيكية (الفلمنكية)', api: 'Flemish (Belgian Dutch)' },
    ]
  },
  { name: 'السواحيلية', code: 'SW', api: 'Swahili (Tanzanian)' },
  { name: 'التاميلية', code: 'TA', api: 'Tamil (Indian)' },
  { name: 'العبرية', code: 'HE', api: 'Hebrew' },
  { name: 'اليابانية', code: 'JA', api: 'Japanese' },
  { name: 'الكورية', code: 'KO', api: 'Korean' },
  { name: 'الروسية', code: 'RU', api: 'Russian' },
  { name: 'التركية', code: 'TR', api: 'Turkish' },
  { name: 'الإيطالية', code: 'IT', api: 'Italian' },
  { name: 'الأفريكانية', code: 'AF', api: 'Afrikaans (South African)' },
  { name: 'الألبانية', code: 'SQ', api: 'Albanian' },
  { name: 'الأمهرية', code: 'AM', api: 'Amharic (Ethiopian)' },
  { name: 'الأوزبكية', code: 'UZ', api: 'Uzbek' },
  { name: 'الأوكرانية', code: 'UK', api: 'Ukrainian' },
  { name: 'الأيرلندية', code: 'GA', api: 'Irish (Irish)' },
  { name: 'الإستونية', code: 'ET', api: 'Estonian' },
  { name: 'الباسكية', code: 'EU', api: 'Basque' },
  { name: 'البشتوية', code: 'PS', api: 'Pashto' },
  { name: 'البلغارية', code: 'BG', api: 'Bulgarian' },
  { name: 'البنجابية', code: 'PA', api: 'Punjabi (Indian)' },
  { name: 'البنغالية', code: 'BN', api: 'Bengali' },
  { name: 'البورمية', code: 'MY', api: 'Burmese' },
  { name: 'البوسنية', code: 'BS', api: 'Bosnian' },
  { name: 'البولندية', code: 'PL', api: 'Polish' },
  { name: 'التايلاندية', code: 'TH', api: 'Thai' },
  { name: 'التشيكية', code: 'CS', api: 'Czech' },
  { name: 'التيلوغوية', code: 'TE', api: 'Telugu' },
  { name: 'الجاليكية', code: 'GL', api: 'Galician' },
  { name: 'الجاوية', code: 'JV', api: 'Javanese' },
  { name: 'الجورجية', code: 'KA', api: 'Georgian' },
  { name: 'الخمير', code: 'KM', api: 'Khmer' },
  { name: 'الدنماركية', code: 'DA', api: 'Danish' },
  { name: 'الرومانية', code: 'RO', api: 'Romanian' },
  { name: 'الزولو', code: 'ZU', api: 'Zulu' },
  { name: 'السلوفاكية', code: 'SK', api: 'Slovak' },
  { name: 'السلوفينية', code: 'SL', api: 'Slovenian' },
  { name: 'السنهالية', code: 'SI', api: 'Sinhala (Sri Lankan)' },
  { name: 'السوندانية', code: 'SU', api: 'Sundanese' },
  { name: 'السويدية', code: 'SV', api: 'Swedish' },
  { name: 'الصربية', code: 'SR', api: 'Serbian' },
  { name: 'الصومالية', code: 'SO', api: 'Somali' },
  { name: 'الغوجاراتية', code: 'GU', api: 'Gujarati (Indian)' },
  { name: 'الفارسية', code: 'FA', api: 'Persian' },
  { name: 'الفلبينية', code: 'TL', api: 'Filipino' },
  { name: 'الفنلندية', code: 'FI', api: 'Finnish' },
  { name: 'الفيتنامية', code: 'VI', api: 'Vietnamese' },
  { name: 'الكازاخية', code: 'KK', api: 'Kazakh' },
  { name: 'الكانادا', code: 'KN', api: 'Kannada' },
  { name: 'الكتالانية', code: 'CA', api: 'Catalan (Spanish)' },
  { name: 'الكرواتية', code: 'HR', api: 'Croatian' },
  { name: 'اللاتفية', code: 'LV', api: 'Latvian' },
  { name: 'الليتوانية', code: 'LT', api: 'Lithuanian' },
  { name: 'المالايالامية', code: 'ML', api: 'Malayalam' },
  { name: 'المالطية', code: 'MT', api: 'Maltese' },
  { name: 'المجرية', code: 'HU', api: 'Hungarian' },
  { name: 'المراثية', code: 'MR', api: 'Marathi' },
  { name: 'المقدونية', code: 'MK', api: 'Macedonian' },
  { name: 'الملايوية', code: 'MS', api: 'Malay' },
  { name: 'المنغولية', code: 'MN', api: 'Mongolian' },
  { name: 'النرويجية', code: 'NO', api: 'Norwegian' },
  { name: 'النيبالية', code: 'NE', api: 'Nepali' },
  { name: 'الهندية', code: 'HI', api: 'Hindi (Indian)' },
  { name: 'اليونانية', code: 'EL', api: 'Greek' },
  { name: 'اللاوية', code: 'LO', api: 'Lao (Laotian)' },
  { name: 'الويلزية', code: 'CY', api: 'English (Welsh)' },
  { name: 'الأرمنية', code: 'HY', api: 'Armenian' },
  { name: 'الأذربيجانية', code: 'AZ', api: 'Azerbaijani' },
  { name: 'الأردية', code: 'UR', api: 'Urdu (Indian)' },
];

// Languages that are not just a single API category but have dialects
function hasDialects(index) {
  return index >= 0 && index < LANGUAGES.length && Array.isArray(LANGUAGES[index].dialects);
}

module.exports = { LANGUAGES, hasDialects };
